name: "task_timer"
description: "Gerencia seu tempo em cada tarefa"
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  duration_picker: ^1.2.0
  flutter_local_notifications: ^17.2.1+1
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  flutter_time_picker_spinner: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  background_fetch: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icon/icon.png
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "lib/assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "lib/assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "lib/assets/icon/icon.png"